apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-dep
  namespace: emp-app
  labels:
    app: emp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp


  template:
    metadata:
      labels:
        app: emp
  
    spec:
      containers:
        - name: django-emp-app
          image: memorydrive/employee-management
          ports:
            - containerPort: 8000
